### ISSUE TITLE
75213595

### ISSUE THREAD

**Issue by zenith2024** [Tenclea/ReYANG#1]
(nvm actually)

**Comment by Tenclea** [comment]
Yeah, make sure to install the correct version of the dependencies so as not to break the app :)

**Comment by MGTro** [comment]
Hey! I don't know where to contact you so I'll ask here, have you thought of making a similar program that generate and checks for server invites instead?

**Comment by Tenclea** [comment]
> Hey! I don't know where to contact you so I'll ask here, have you thought of making a similar program that generate and checks for server invites instead?

I already did this as a side project once, but we never made anything public. Why are you asking ?

**Comment by MGTro** [comment]
> > Hey! I don't know where to contact you so I'll ask here, have you thought of making a similar program that generate and checks for server invites instead?
> 
> I already did this as a side project once, but we never made anything public. Why are you asking ?

Someone was bulk buying valid invites so it could've been useful. But if it's private it is what it is

**Comment by infixite** [comment]
can i have the invites program??

**Comment by Tenclea** [comment]
@infixite I can re-make one and publish it, if you're still interested

**Comment by infixite** [comment]
@Tenclea that would be appreciated

**Comment by MGTro** [comment]
@Tenclea so how did it go?
