### ISSUE TITLE
very slow

### ISSUE THREAD

**Issue by NoahEH11** [Tenclea/ReYANG#10]
the nitro gen is going very slow, 18 proxies, 38 attempts in 4 minutes, (~9/min) it says, why is it so slow?

**Comment by Tenclea** [comment]
You must have run out of good proxies. You can do a few things:
- find or purchase some proxies online
- lower the amount of threads in the config file
- increase the amount of maximum downloaded proxies in the config file as well

Hope this helps!

**Comment by Abobo7** [comment]
How to use a custom proxy
