### ISSUE TITLE
Stuck at Proxy check 1

### ISSUE THREAD

**Issue by Woogiesii** [Tenclea/ReYANG#3]
![image](https://github.com/Tenclea/ReYANG/assets/70749185/88d5adaa-f629-496e-963e-d8a579f980c9)
Why am i always stuck at here?

**Comment by Tenclea** [comment]
Do you put in your personal proxy list, or do you let the app download them itself ?

**Comment by Woogiesii** [comment]
> Do you put in your personal proxy list, or do you let the app download them itself ?

i'm trying with 2 options 1. with the app download and 2. from my personal proxy list. it came the same

**Comment by hteppl** [comment]
+

**Comment by Magic-Hole** [comment]
proxy scrapper not working ?

**Comment by Tenclea** [comment]
May or may not be fixed in the next release, let me know if it still isn't

**Comment by Tenclea** [comment]
Should be fixed in [v3.3.5](https://github.com/Tenclea/ReYANG/releases/tag/v3.3.5). let me know if the issue still occurs
