### ISSUE TITLE
"Could not scrape proxies 

### ISSUE THREAD

**Issue by 20212801121** [Tenclea/ReYANG#6]
![Screenshot 2024-03-23 091419](https://github.com/Tenclea/ReYANG/assets/164637847/e1b6d6ab-3296-4d5c-880a-236270ce87db)

shows that error message and not finding any working links approximately how long does it take to find a working link and what's the next step?

**Comment by iamm3u** [comment]
dude it might take days to find a working code

**Comment by SkyKingPX** [comment]
Same Problem.
I checked the page and it seems to be taken down

**Comment by Tenclea** [comment]
On it, a fix should be available soon

**Comment by Tenclea** [comment]
Fixed in [v3.3.5](https://github.com/Tenclea/ReYANG/releases/tag/v3.3.5)!
