### ISSUE TITLE
Windows keeps deleting the application.

### ISSUE THREAD

**Issue by XanderHGX** [Tenclea/ReYANG#8]
Whenever I unzip it Windows deletes the software within a few seconds. Any solutions?

**Comment by Tenclea** [comment]
Must be an AV issue, i'll try to update the app soon

**Comment by Tenclea** [comment]
Should be fixed in the last update? I don't really know why it works for a while after updating, lmk if/when windows starts deleting it again

**Comment by Tenclea** [comment]
Closed until further notice
